import { Merchant, Review, User } from './types'

// 当前用户
export const currentUser: User = {
  id: 'u1',
  nickname: '吃货小王',
  avatar: '',
  level: 3,
  levelName: '美食家',
  authStatus: 'verified',
  school: '北京大学',
  reviewCount: 23,
  likeReceived: 45,
  joinDate: '2025-09-01',
  preferences: ['辣', '面食', '奶茶'],
}

// 商户数据
export const merchants: Merchant[] = [
  {
    id: 'm1',
    name: '学一食堂·麻辣香锅',
    category: '食堂',
    subCategory: '麻辣香锅',
    address: '校内学一食堂二楼C区',
    avgPrice: 18,
    rating: 4.5,
    ratings: { taste: 4.6, hygiene: 4.3, service: 4.2, value: 4.8, portion: 4.5 },
    reviewCount: '128',
    images: ['/placeholder-food-1.jpg'],
    openHours: '10:30-13:30, 16:30-19:30',
    tags: ['分量大', '出餐快', '性价比高'],
    popularDishes: [
      { name: '麻辣香锅（大份）', price: 22, mentions: 89 },
      { name: '麻辣香锅（小份）', price: 15, mentions: 56 },
      { name: '酸辣粉', price: 10, mentions: 34 },
    ],
    distance: 0.2,
  },
  {
    id: 'm2',
    name: '老张家烤冷面',
    category: '小吃街',
    subCategory: '小吃',
    address: '北门小吃街第3家',
    avgPrice: 8,
    rating: 4.7,
    ratings: { taste: 4.8, hygiene: 4.0, service: 4.5, value: 4.9, portion: 4.6 },
    reviewCount: '256',
    images: ['/placeholder-food-2.jpg'],
    openHours: '16:00-23:00',
    tags: ['排队王', '必吃', '夜宵首选'],
    popularDishes: [
      { name: '招牌烤冷面', price: 8, mentions: 200 },
      { name: '芝士烤冷面', price: 12, mentions: 88 },
      { name: '火鸡面烤冷面', price: 10, mentions: 65 },
    ],
    distance: 0.5,
  },
  {
    id: 'm3',
    name: '一点点奶茶',
    category: '饮品甜品',
    subCategory: '奶茶',
    address: '东门商业街A102',
    avgPrice: 15,
    rating: 4.3,
    ratings: { taste: 4.4, hygiene: 4.5, service: 4.0, value: 4.1, portion: 4.3 },
    reviewCount: '189',
    images: ['/placeholder-food-3.jpg'],
    openHours: '09:00-22:00',
    tags: ['品种多', '可加料', '下午茶'],
    popularDishes: [
      { name: '波霸奶茶', price: 13, mentions: 120 },
      { name: '四季春茶', price: 10, mentions: 78 },
      { name: '冰淇淋红茶', price: 16, mentions: 55 },
    ],
    distance: 0.8,
  },
  {
    id: 'm4',
    name: '黄焖鸡米饭',
    category: '周边餐馆',
    subCategory: '中式快餐',
    address: '西门外50米',
    avgPrice: 16,
    rating: 4.1,
    ratings: { taste: 4.2, hygiene: 3.8, service: 3.9, value: 4.5, portion: 4.3 },
    reviewCount: '95',
    images: ['/placeholder-food-4.jpg'],
    openHours: '10:00-21:00',
    tags: ['经典', '下饭', '实惠'],
    popularDishes: [
      { name: '黄焖鸡米饭', price: 16, mentions: 80 },
      { name: '黄焖排骨米饭', price: 20, mentions: 45 },
      { name: '黄焖牛肉米饭', price: 22, mentions: 30 },
    ],
    distance: 0.6,
  },
  {
    id: 'm5',
    name: '重庆小面馆',
    category: '周边餐馆',
    subCategory: '面食',
    address: '南门小吃街拐角',
    avgPrice: 14,
    rating: 4.6,
    ratings: { taste: 4.8, hygiene: 4.2, service: 4.3, value: 4.7, portion: 4.5 },
    reviewCount: '167',
    images: ['/placeholder-food-5.jpg'],
    openHours: '07:00-21:00',
    tags: ['正宗', '辣', '早餐好选择'],
    popularDishes: [
      { name: '重庆小面', price: 12, mentions: 130 },
      { name: '豌杂面', price: 14, mentions: 90 },
      { name: '酸辣粉', price: 10, mentions: 70 },
    ],
    distance: 0.4,
  },
  {
    id: 'm6',
    name: '学二食堂·铁板饭',
    category: '食堂',
    subCategory: '铁板饭',
    address: '校内学二食堂一楼',
    avgPrice: 15,
    rating: 4.2,
    ratings: { taste: 4.3, hygiene: 4.4, service: 3.8, value: 4.5, portion: 4.0 },
    reviewCount: '76',
    images: ['/placeholder-food-6.jpg'],
    openHours: '11:00-13:00, 17:00-19:00',
    tags: ['滋滋响', '现做', '排队'],
    popularDishes: [
      { name: '黑椒牛排铁板饭', price: 18, mentions: 50 },
      { name: '铁板炒饭', price: 12, mentions: 40 },
      { name: '铁板意面', price: 15, mentions: 25 },
    ],
    distance: 0.3,
  },
  {
    id: 'm7',
    name: '赵记烧烤',
    category: '夜市',
    subCategory: '烧烤',
    address: '北门夜市摊位B区',
    avgPrice: 25,
    rating: 4.4,
    ratings: { taste: 4.6, hygiene: 3.9, service: 4.2, value: 4.3, portion: 4.5 },
    reviewCount: '143',
    images: ['/placeholder-food-7.jpg'],
    openHours: '18:00-02:00',
    tags: ['夜宵', '烤串', '聚会'],
    popularDishes: [
      { name: '羊肉串（10串）', price: 20, mentions: 110 },
      { name: '烤鸡翅', price: 6, mentions: 80 },
      { name: '烤茄子', price: 8, mentions: 60 },
    ],
    distance: 0.5,
  },
  {
    id: 'm8',
    name: '沙县小吃',
    category: '周边餐馆',
    subCategory: '中式快餐',
    address: '西门外100米',
    avgPrice: 12,
    rating: 3.9,
    ratings: { taste: 3.8, hygiene: 4.0, service: 3.9, value: 4.3, portion: 3.8 },
    reviewCount: '62',
    images: ['/placeholder-food-8.jpg'],
    openHours: '06:30-22:00',
    tags: ['早餐', '实惠', '经典'],
    popularDishes: [
      { name: '蒸饺', price: 8, mentions: 45 },
      { name: '拌面', price: 7, mentions: 40 },
      { name: '馄饨', price: 8, mentions: 35 },
    ],
    distance: 0.6,
  },
  {
    id: 'm9',
    name: '蜜雪冰城',
    category: '饮品甜品',
    subCategory: '冰淇淋/饮品',
    address: '北门小吃街入口',
    avgPrice: 6,
    rating: 4.0,
    ratings: { taste: 4.0, hygiene: 4.2, service: 3.8, value: 4.8, portion: 3.9 },
    reviewCount: '210',
    images: ['/placeholder-food-9.jpg'],
    openHours: '09:30-22:30',
    tags: ['便宜', '冰淇淋', '夏天必备'],
    popularDishes: [
      { name: '柠檬水', price: 4, mentions: 180 },
      { name: '摩天脆脆冰淇淋', price: 3, mentions: 150 },
      { name: '珍珠奶茶', price: 6, mentions: 100 },
    ],
    distance: 0.5,
  },
  {
    id: 'm10',
    name: '学三食堂·清真窗口',
    category: '食堂',
    subCategory: '清真',
    address: '校内学三食堂二楼',
    avgPrice: 14,
    rating: 4.3,
    ratings: { taste: 4.4, hygiene: 4.5, service: 4.1, value: 4.4, portion: 4.2 },
    reviewCount: '54',
    images: ['/placeholder-food-10.jpg'],
    openHours: '11:00-13:30, 17:00-19:30',
    tags: ['清真', '大盘鸡', '拉面'],
    popularDishes: [
      { name: '大盘鸡', price: 25, mentions: 35 },
      { name: '牛肉拉面', price: 12, mentions: 30 },
      { name: '羊肉泡馍', price: 18, mentions: 20 },
    ],
    distance: 0.4,
  },
]

// 评价数据
export const reviews: Review[] = [
  {
    id: 'r1',
    userId: 'u1',
    userName: '吃货小王',
    userAvatar: '',
    userLevel: 3,
    merchantId: 'm1',
    merchantName: '学一食堂·麻辣香锅',
    ratings: { taste: 5, hygiene: 4, service: 4, value: 5, portion: 5 },
    overallRating: 4.7,
    content:
      '学一楼的麻辣香锅真的是性价比之王！大份才22块钱，肉和菜的量都很足。推荐加宽粉和午餐肉，吸满了汤汁特别入味。唯一的小缺点是中午排队太长了，建议11点前去。阿姨手速很快，基本5分钟就能出餐。',
    images: [],
    likes: 23,
    replies: [
      {
        id: 'rp1',
        userId: 'u3',
        userName: '面食爱好者',
        content: '确实！加一份方便面也超好吃',
        createdAt: '2025-10-15T12:30:00',
      },
    ],
    createdAt: '2025-10-15T11:20:00',
    isVerified: true,
    isFeatured: true,
    richness: 1.2,
  },
  {
    id: 'r2',
    userId: 'u2',
    userName: '每天都要喝奶茶',
    userAvatar: '',
    userLevel: 4,
    merchantId: 'm2',
    merchantName: '老张家烤冷面',
    ratings: { taste: 5, hygiene: 4, service: 5, value: 5, portion: 5 },
    overallRating: 4.8,
    content:
      '北门烤冷面之神！老板做了十几年了，手艺没得说。酱料是秘制的，酸甜辣度刚刚好。芝士款拉丝效果绝了，拍照发朋友圈必点。建议避开晚高峰，不然要排20分钟以上。冬天来一份热乎乎的烤冷面，幸福感拉满。',
    images: [],
    likes: 45,
    replies: [],
    createdAt: '2025-10-14T19:45:00',
    isVerified: true,
    isFeatured: true,
    richness: 1.1,
  },
  {
    id: 'r3',
    userId: 'u3',
    userName: '面食爱好者',
    userAvatar: '',
    userLevel: 2,
    merchantId: 'm5',
    merchantName: '重庆小面馆',
    ratings: { taste: 5, hygiene: 4, service: 4, value: 5, portion: 5 },
    overallRating: 4.7,
    content:
      '作为一个重庆人，这家小面算是比较正宗的了。面条劲道，红油香而不腻。豌杂面里的豌豆炖得很烂，杂酱也很香。不能吃辣的同学建议点微辣，因为他们的微辣已经相当于外面的中辣了。价格也很良心，学生党友好。',
    images: [],
    likes: 18,
    replies: [
      {
        id: 'rp2',
        userId: 'u5',
        userName: '不能吃辣',
        content: '微辣都把我辣到了哈哈，但是真的好吃',
        createdAt: '2025-10-13T13:00:00',
      },
      {
        id: 'rp3',
        userId: 'u1',
        userName: '吃货小王',
        content: '同重庆人认证！确实正宗',
        createdAt: '2025-10-13T14:20:00',
      },
    ],
    createdAt: '2025-10-13T12:15:00',
    isVerified: true,
    isFeatured: false,
    richness: 1.1,
  },
  {
    id: 'r4',
    userId: 'u4',
    userName: '省钱达人',
    userAvatar: '',
    userLevel: 3,
    merchantId: 'm9',
    merchantName: '蜜雪冰城',
    ratings: { taste: 4, hygiene: 4, service: 4, value: 5, portion: 4 },
    overallRating: 4.2,
    content:
      '4块钱的柠檬水，这个价格谁不爱？夏天一天一杯不是梦。冰淇淋也很划算，3块钱的甜筒比肯德基的还大。唯一需要注意的是高峰期要等比较久，建议错峰去。甜蜜蜜的歌已经刻进DNA了。',
    images: [],
    likes: 32,
    replies: [],
    createdAt: '2025-10-12T16:30:00',
    isVerified: true,
    isFeatured: false,
    richness: 1.0,
  },
  {
    id: 'r5',
    userId: 'u5',
    userName: '不能吃辣',
    userAvatar: '',
    userLevel: 1,
    merchantId: 'm6',
    merchantName: '学二食堂·铁板饭',
    ratings: { taste: 4, hygiene: 5, service: 3, value: 5, portion: 4 },
    overallRating: 4.2,
    content:
      '黑椒牛排铁板饭推荐！端上来滋滋响特别有食欲。牛排虽然不是真牛排但是味道不错，黑椒汁很浓郁。饭量正常，男生可能需要加饭。排队时间看运气，有时候10分钟有时候半小时。',
    images: [],
    likes: 8,
    replies: [],
    createdAt: '2025-10-11T12:00:00',
    isVerified: false,
    isFeatured: false,
    richness: 1.0,
  },
  {
    id: 'r6',
    userId: 'u6',
    userName: '夜猫子',
    userAvatar: '',
    userLevel: 4,
    merchantId: 'm7',
    merchantName: '赵记烧烤',
    ratings: { taste: 5, hygiene: 4, service: 4, value: 4, portion: 5 },
    overallRating: 4.5,
    content:
      '期末复习到深夜的最佳伴侣！赵记烧烤开到凌晨2点，羊肉串烤得外焦里嫩，撒上孜然辣椒面绝了。烤茄子蒜香味十足，配上一瓶冰啤简直是人间美味。建议4人以上一起去，可以多点几个品种。人均25左右，聚餐性价比很高。',
    images: [],
    likes: 27,
    replies: [
      {
        id: 'rp4',
        userId: 'u2',
        userName: '每天都要喝奶茶',
        content: '考完试必须去搓一顿！',
        createdAt: '2025-10-10T23:30:00',
      },
    ],
    createdAt: '2025-10-10T22:45:00',
    isVerified: true,
    isFeatured: true,
    richness: 1.1,
  },
]

// 用户等级配置
export const levelConfig = [
  { level: 1, name: '新芽', icon: '🌱', requirement: '完成注册+学籍认证', weight: 0.5 },
  { level: 2, name: '食客', icon: '🍜', requirement: '发布5条有效评价', weight: 0.7 },
  { level: 3, name: '美食家', icon: '👨‍🍳', requirement: '20条评价 + 10个点赞', weight: 0.85 },
  { level: 4, name: '品鉴官', icon: '🏅', requirement: '50条评价 + 50个点赞', weight: 1.0 },
  { level: 5, name: '校园美食达人', icon: '⭐', requirement: '100条评价 + 社区贡献', weight: 1.2 },
]

// 评分维度配置
export const ratingDimensions = [
  { key: 'taste', label: '口味', icon: '👅', weight: 0.35 },
  { key: 'hygiene', label: '卫生', icon: '🧹', weight: 0.2 },
  { key: 'service', label: '服务', icon: '🤝', weight: 0.15 },
  { key: 'value', label: '性价比', icon: '💰', weight: 0.2 },
  { key: 'portion', label: '分量', icon: '📏', weight: 0.1 },
]

// 商户分类配置
export const categoryConfig = [
  { key: '全部', icon: '🏠', description: '所有商户' },
  { key: '食堂', icon: '🏫', description: '校内食堂档口' },
  { key: '小吃街', icon: '🍢', description: '校门口小吃' },
  { key: '周边餐馆', icon: '🍚', description: '校园周边餐厅' },
  { key: '饮品甜品', icon: '🧋', description: '奶茶咖啡甜品' },
  { key: '夜市', icon: '🌙', description: '夜市摊位' },
]
